spring:
  application:
    name: plm
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
  session:
    timeout: 604800 # 7 days
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hzhg.plm
  swagger-ui:
    enabled: true
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
management:
  endpoints:
    web:
      exposure:
        include: "*"